### ISSUE TITLE
repos too fine grained?

### ISSUE THREAD

**Issue by bjorn-stevens** [orcestra-campaign/flights#11]
I was wondering if the repo's are too fine grained... the scripts that we might use for flight-reporting could go here as well, but would not be intuitive to find.

Suggest renaming flight-analysis and then include directories for planning and reporting, and maybe other things as they arise.

**Comment by JuliaWindmiller1987** [comment]
The pull request `Restructures repository #13` now creates three new folders to have folders for during and post flights as well before.
